trial: "exp1" # going to be a header controlling where to save
batch_size: 32
num_epochs: 25

# model related
model:
  type: 'resnet18'

# optimizer related
optim:
  type: 'Adam' # or Momentum
  lr: 0.001
  amsgrad: True
  momentum: 0.9
  weight_decay: 0.001