CMD := python main.py -c config.yaml

test:
	${CMD} --trial "test" --batch_size 16 --num_epochs 1 --model_type "simplecnn"

cnn:
	${CMD} --trial "exp1" --batch_size 32 --num_epochs 50
	${CMD} --trial "exp2" --batch_size 32 --num_epochs 70
	${CMD} --trial "exp3" --batch_size 32 --num_epochs 90
	${CMD} --trial "exp4" --batch_size 64 --num_epochs 50
	${CMD} --trial "exp5" --batch_size 64 --num_epochs 70
	${CMD} --trial "exp6" --batch_size 64 --num_epochs 90

resnet:
	${CMD} --trial "exp1" --batch_size 32 --num_epochs 20 --model_type "resnet18" --optim_lr 0.01
	${CMD} --trial "exp2" --batch_size 64 --num_epochs 20 --model_type "resnet18" --optim_lr 0.01
	${CMD} --trial "exp3" --batch_size 32 --num_epochs 30 --model_type "resnet18" --optim_lr 0.01
	${CMD} --trial "exp4" --batch_size 64 --num_epochs 30 --model_type "resnet18" --optim_lr 0.01
	${CMD} --trial "exp5" --batch_size 32 --num_epochs 20 --model_type "resnet18" --optim_lr 0.001
	${CMD} --trial "exp6" --batch_size 32 --num_epochs 30 --model_type "resnet18" --optim_lr 0.001
